'use client'
import { Inter } from "next/font/google";
import "./globals.css";
import {CourseProvider} from '../context/CourseContext';
const inter = Inter({ subsets: ["latin"] });

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <CourseProvider>
      <html lang="en" suppressHydrationWarning={true}>
        <body className={inter.className}>{children}</body>
      </html>
    </CourseProvider>
  );
}
